import { useEffect, useState } from "react";
import "./AdminExperience.css";
function AdminExperience(){
 const [items,setItems]=useState([]); const [loading,setLoading]=useState(true);
 const load=async()=>{try{const r=await fetch("https://career-canvas-portfolio.onrender.com/experience"); if(!r.ok)throw new Error(); setItems(await r.json());}catch(e){console.error(e)}finally{setLoading(false)}};
 useEffect(()=>{if(sessionStorage.getItem("adminLoggedIn")!=="true"){window.location.href="/admin/login";return;} load();},[]);
 const del=async id=>{if(!window.confirm("Delete this experience?"))return; try{const r=await fetch(`http://localhost:8080/experience/${id}`,{method:"DELETE",credentials:"include"}); if(!r.ok)throw new Error(); setItems(v=>v.filter(x=>x.id!==id));}catch(e){alert("Unable to delete experience")}};
 return <div className="admin-experience-page"><header className="admin-experience-header"><div><span className="admin-experience-label">ADMIN</span><h1>Manage Experience</h1><p>Manage your professional experience.</p></div><div className="admin-experience-actions"><button className="primary" onClick={()=>window.location.href="/admin/experience/add"}>+ Add Experience</button><button onClick={()=>window.location.href="/admin/dashboard"}>Dashboard</button></div></header><main className="admin-experience-content">{loading?<p className="admin-experience-status">Loading experience...</p>:items.length===0?<p className="admin-experience-status">No experience found.</p>:<div className="admin-experience-grid">{items.map(x=><div className="admin-experience-card" key={x.id}><span className="admin-experience-number">#{x.id}</span><h2>{x.role}</h2><h3>{x.company}</h3><p>{x.description}</p><div className="admin-experience-meta">{x.startDate} - {x.endDate || "Present"}</div><div className="admin-experience-buttons"><button className="admin-experience-edit" onClick={()=>window.location.href=`/admin/experience/edit/${x.id}`}>Edit</button><button className="admin-experience-delete" onClick={()=>del(x.id)}>Delete</button></div></div>)}</div>}</main></div>}
export default AdminExperience;
